### ISSUE TITLE
Cannot compile/run after installing

### ISSUE THREAD

**Issue by davbaron** [xon52/x5-notify#1]
Hello, I’ve been progressing with my app…specifically using the ‘modals’ to hold a somewhat complex ‘form’ component.  All is working fine with it – very nice job.  That said, I would like to integrate x5-Notify into the page.  I used npm to install the package from github… then ‘registered’ the package as instructed.  However, when I try to run (simply ‘compiling/navigating to home page’) I get an error (and the site thus will not load):

```
index.js:1 Uncaught TypeError: t.registerModule is not a function
    at t.default (index.js:1)
    at Function.Vue.use (vue.runtime.esm.js:5109)
    at Module../src/main.js (main.js:34)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Object.1 (app.js:10635)
    at __webpack_require__ (bootstrap:784)
    at checkDeferredModules (bootstrap:45)
    at bootstrap:860
    at bootstrap:860
```

I’m guessing this is coming from your index.js file where you try to:  
`store.registerModule(‘x5/n’, PluginStore)`

Here is the pertinent stuff from my code:

From main.js:

At very top:
```
import Vue from 'vue'
import App from './App.vue'
import router from './router'
import store from './store/store'
….
import x5Modal from 'x5-modal'
import x5Notify from 'x5-notify'
```

…mid-way down:
`Vue.use(x5Modal, x5Notify, store)`

From App.vue, near end of ‘template’ markup:
```
    <x5-modals></x5-modals>
    <x5-notify></x5-notify>
  </v-app>
</template>
```

from package.json, within ‘dependencies’:
```
"x5-modal": "^0.2.12",
"x5-notify": "^0.3.7"
```

Nothing is jumping out at me... thoughts?

-David

**Comment by xon52** [comment]
Yup: `Vue.use(x5Modal, x5Notify, store)` is not correct. [Vue.use()](https://vuejs.org/v2/guide/plugins.html#Using-a-Plugin) only handles one plugin at a time. The first parameter is the **plugin install function** (the default export of my packages), and the second is any **options** for that plugin. So it should looks like so:
```js
import Vue from 'vue'
import App from './ui/App.vue'
import store from './store'
import x5Notify from 'x5-notify'
import x5Modal from 'x5-modal'

Vue.use(x5Notify, store)
Vue.use(x5Modal, store)

new Vue({
  store,
  render: (h) => h(App),
}).$mount('#app')
```

**Comment by davbaron** [comment]
Thanks man, that was it of course... well, almost.  The 'sample' code uses what I'm guessing is an older syntax, i.e., this.$notice('success','My message').  I was getting errors, i.e., $notice is not a known function. So, I re-reviewed the source, and sure enough, now it is called $notify, which of course works fine. Thanks again!  I'm closing this out (but would suggest updating the docs).

**Comment by xon52** [comment]
Ah yes. Just updated the readme. Thanks for pointing that out. I think the original was $notice.
